### ISSUE TITLE
dataset NELL186

### ISSUE THREAD

**Issue by loveyoghurt123** [arthurcgusmao/SFE#2]
Hello! I want the NELL186 dataset. I can not find on the network and in your project. Can you give me a way?Thank you.

**Comment by arthurcgusmao** [comment]
Hi @loveyoghurt123 , please refer to this repo: [XKE/benchmarks](https://github.com/arthurcgusmao/XKE/tree/xke-master/benchmarks)

Please notice that I have not thoroughly tested this code; it was a side project that would eventually turn into a publication that I decide not to follow through with. If you have contributions to the code please don't hesitate to share them :)
